routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware'=>'auth'],function(){
	Route::get('/','HomeController@index')->name('home');

Route::get('/home', 'HomeController@index');
Route::post('/absen', 'HomeController@absen');
Route::resource('/jabatan', 'JabatanController');
Route::resource('/pendidikan', 'PendidikanController');
Route::resource('/pegawai', 'PegawaiController');

});

app/Jabatan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Jabatan extends Model
{
    protected $table = 'jabatan';
    protected $primaryKey = 'id_jabatan';

    public function pegawai() {
    	return $this->hasMany('App\Pegawai', 'id_jabatan');
    }
}

app/Http/Controllers/JabatanController.php
<?php

namespace App\Http\Controllers;
use App\Jabatan;

use Illuminate\Http\Request;

class JabatanController extends Controller
{
    public function index()
    {
        $jabatan = Jabatan::all();
        return view('jabatan/index', ['jabatan'=>$jabatan, 'no'=>0]);
    }

   
    public function create()
    {
        return view('jabatan/create');
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            'nama' => 'required|alpha|min:2|max:50'
        ],[
            'nama.required' => 'Nama jabatan tidak boleh kosong'
        ]);

        $jabatan = new Jabatan;
        $jabatan->nama_jabatan = $request['nama'];
        $jabatan->save();

        return redirect()
            ->route('jabatan.index')
            ->with('success','Data berhasil ditambahkan');
    }

   
    public function edit($id)
    {
        $jabatan = Jabatan::find($id);
        return view('jabatan/edit', ['jabatan'=>$jabatan]);
    }

 
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'nama' => 'required|alpha|min:2|max:50'
        ],[
            'nama.required' => 'Nama jabatan tidak boleh kosong'
        ]);

        $jabatan = Jabatan::find($id);
        $jabatan->nama_jabatan = $request['nama'];
        $jabatan->update();

        return redirect()
            ->route('jabatan.index')
            ->with('success','Data berhasil diedit');
    }


    public function destroy($id)
    {
        $jabatan = Jabatan::find($id);
        $jabatan->delete();

        return redirect()
            ->route('jabatan.index')
            ->with('success','Data berhasil dihapus');
    }
}

resources/views/jabatan/create.blade.php
@extends('layouts.template')

@section('content')

<h4 class="mt-2">Tambah Jabatan</h4>
<hr>

@if ($errors->any())
	<div class="alert alert-danger pb-0">
		<ul>
			@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
@endif

<form method="post" action="{{ route('jabatan.store') }}">
	{{ csrf_field() }}

	<div class="form-group row">
		<label for="nama" class="col-sm-2 col-form-label">Nama Jabatan</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" id="nama" name="nama" autocomplete="off" autofocus="">
		</div>
	</div>

	<button type="submit" class="btn btn-outline-info btn-fw"><i class="oi oi-task"></i>Simpan</button>
	<button type="reset" class="btn btn-outline-danger btn-fw"><i class="oi oi-circle"></i>Batal</button>

</form>
@endsection 

resources/views/jabatan/edit.blade.php
@extends('layouts.template')

@section('content')
<h4 class="mt-2">Edit Jabatan</h4>
<hr>

@if ($errors->any())
	<div class="alert alert-danger pb-0">
		<ul>
			@foreach ($errors->all() as $error)
			<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
@endif

<form method="post" action="{{ route('jabatan.update', $jabatan['id_jabatan']) }}">
	{{ method_field('PUT') }}
	{{ csrf_field() }}

	<div class="form-group row">
		<label for="nama" class="col-sm-2 col-form-label">Nama Jabatan</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" id="nama" name="nama" autocomplete="off" autofocus="" value="{{ $jabatan['nama_jabatan'] }}">
		</div>
	</div>

	<button type="submit" class="btn btn-outline-info btn-fw"><i class="oi oi-task"></i>Simpan</button>
	<button type="reset" class="btn btn-outline-danger btn-fw"><i class="oi oi-circle-x"></i>Batal</button>

</form>
@endsection

resources/views/jabatan/index.blade.php
@extends('layouts.template')
@section('content')

<h4 class="mt-2">Data Jabatan</h4>
<hr>
<a class="btn btn-inverse-primary btn-fw" href="{{ route('jabatan.create') }}"><i class="oi oi-plus"></i>Tambah</a>

@if ($message = Session::get('success'))
	<div class="alert alert-success mt-3 pb-0">
		<p>{{ $message }}</p>
	</div>
@endif

<div class="table-responsive mt-3">
<table class="table table-striped table-hover table-bordered">
	<thead>
		<tr>
			<th>No</th>
			<th>Nama Jabatan</th>
			<th>Aksi</th>
		</tr>
	</thead>
	<tbody>
		
@foreach($jabatan as $data)
	<tr>
		<td><?php echo ++$no ?></td>
		<td>{{$data['nama_jabatan']}}</td>
		<td>
			<a class="btn btn-outline-success btn-fw" href="{{ route('jabatan.edit', $data['id_jabatan']) }}"> <i class="oi oi-pencil"></i>Edit</a>
			<form class="d-inline" method="post" action="{{ route('jabatan.destroy', $data['id_jabatan']) }}">
				{{ method_field('DELETE') }}
				{{ csrf_field() }}
				<button type="submit" class="btn btn-outline-danger btn-fw"> <i class="oi oi-trash"></i>Hapus</button>
			</form>
		</td>
	</tr>
@endforeach

	</tbody>
</table>
</div>

@endsection