routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware'=>'auth'],function(){
	Route::get('/','HomeController@index')->name('home');

Route::get('/home', 'HomeController@index');
Route::post('/absen', 'HomeController@absen');
Route::resource('/jabatan', 'JabatanController');
Route::resource('/pendidikan', 'PendidikanController');
Route::resource('/pegawai', 'PegawaiController');

});

app/Pendidikan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pendidikan extends Model
{
    protected $table = 'pendidikan';
    protected $primaryKey = 'id_pendidikan';

    public function pendidikan() {
    	return $this->hasMany('App\Pegawai', 'id_pendidikan');
    }
}

app/Http/Controllers/PendidikanController.php
<?php  

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Pendidikan;

class PendidikanController extends Controller
{
    public function index()
    {
        $pendidikan = Pendidikan::all();
        return view('pendidikan/index', ['pendidikan'=>$pendidikan, 'no'=>0]);
    }

   
    public function create()
    {
        return view('pendidikan/create');
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            'nama' => 'required|alpha|max:50'
        ],[
            'nama.required' => 'Nama pendidikan tidak boleh kosong'
        ]);

        $pendidikan = new Pendidikan;
        $pendidikan->nama_pendidikan = $request['nama'];
        $pendidikan->save();

        return redirect()
            ->route('pendidikan.index')
            ->with('success','Data berhasil ditambahkan');
    }

   
    public function edit($id)
    {
        $pendidikan = Pendidikan::find($id);
        return view('pendidikan/edit', ['pendidikan'=>$pendidikan]);
    }

 
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'nama' => 'required|alpha|max:50'
        ],[
            'nama.required' => 'Nama pendidikan tidak boleh kosong'
        ]);

        $pendidikan = Pendidikan::find($id);
        $pendidikan->nama_pendidikan = $request['nama'];
        $pendidikan->update();

        return redirect()
            ->route('pendidikan.index')
            ->with('success','Data berhasil diedit');
    }


    public function destroy($id)
    {
        $pendidikan = Pendidikan::find($id);
        $pendidikan->delete();

        return redirect()
            ->route('pendidikan.index')
            ->with('success','Data berhasil dihapus');
    }
}

resources/views/pendidikan/create.blade.php
@extends('layouts.template')

@section('content')

<h4 class="mt-2">Tambah Pendidikan</h4>
<hr>

@if ($errors->any())
	<div class="alert alert-danger pb-0">
		<ul>
			@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
@endif

<form method="post" action="{{ route('pendidikan.store') }}">
	{{ csrf_field() }}

	<div class="form-group row">
		<label for="nama" class="col-sm-2 col-form-label">Nama Pendidikan</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" id="nama" name="nama" autocomplete="off" autofocus="">
		</div>
	</div>

	<button type="submit" class="btn btn-outline-info btn-fw"><i class="oi oi-task"></i>Simpan</button>
	<button type="reset" class="btn btn-outline-danger btn-fw"><i class="oi oi-circle"></i>Batal</button>

</form>
@endsection 

resources/views/pendidikan/edit.blade.php
@extends('layouts.template')

@section('content')
<h4 class="mt-2">Edit Pendidikan</h4>
<hr>

@if ($errors->any())
	<div class="alert alert-danger pb-0">
		<ul>
			@foreach ($errors->all() as $error)
			<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
@endif

<form method="post" action="{{ route('pendidikan.update', $pendidikan['id_pendidikan']) }}">
	{{ method_field('PUT') }}
	{{ csrf_field() }}
	<div class="form-group row">
		<label for="nama" class="col-sm-2 col-form-label">Nama Pendidikan</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" id="nama" name="nama" autocomplete="off" autofocus="" value="{{ $pendidikan['nama_pendidikan'] }}">
		</div>
	</div>

	<button type="submit" class="btn btn-outline-info btn-fw"><i class="oi oi-task"></i>Simpan</button>
	<button type="reset" class="btn btn-outline-danger btn-fw"><i class="oi oi-circle-x"></i>Batal</button>

</form>
@endsection

resources/views/pendidikan/index.blade.php
@extends('layouts.template')
@section('content')

<h4 class="mt-2">Data Pendidikan</h4>
<hr>
<a class="btn btn-inverse-primary btn-fw" href="{{ route('pendidikan.create') }}"><i class="oi oi-plus"></i>Tambah</a>

@if ($message = Session::get('success'))
	<div class="alert alert-success mt-3 pb-0">
		<p>{{ $message }}</p>
	</div>
@endif

<div class="table-responsive mt-3">
<table class="table table-striped table-hover table-bordered">
	<thead>
		<tr>
			<th>No</th>
			<th>Nama Pendidikan</th>
			<th>Aksi</th>
		</tr>
	</thead>
	<tbody>
		
@foreach($pendidikan as $data)
	<tr>
		<td><?php echo ++$no ?></td>
		<td>{{$data['nama_pendidikan']}}</td>
		<td>
			<a class="btn btn-outline-success btn-fw" href="{{ route('pendidikan.edit', $data['id_pendidikan']) }}"> <i class="oi oi-pencil"></i>Edit</a>
			<form class="d-inline" method="post" action="{{ route('pendidikan.destroy', $data['id_pendidikan']) }}">
				{{ method_field('DELETE') }}
				{{ csrf_field() }}
				<button type="submit" class="btn btn-outline-danger btn-fw"> <i class="oi oi-trash"></i>Hapus</button>
			</form>
		</td>
	</tr>
@endforeach

	</tbody>
</table>
</div>

@endsection