routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware'=>'auth'],function(){
	Route::get('/','HomeController@index')->name('home');

Route::get('/home', 'HomeController@index');
Route::post('/absen', 'HomeController@absen');
Route::resource('/jabatan', 'JabatanController');
Route::resource('/pendidikan', 'PendidikanController');
Route::resource('/pegawai', 'PegawaiController');

});

app/Pegawai.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pegawai extends Model
{
    protected $table = 'users';
    protected $primaryKey = 'id';

    public function jabatan(){
    	return $this->belongsTo('App/Jabatan');
    }

    public function pendidikan(){
    	return $this->belongsTo('App/Pendidikan');
    }
    
}

app/Http/Controllers/PegawaiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Pegawai;
use App\Jabatan; 
use App\Pendidikan;

class PegawaiController extends Controller
{
    public function index() {
    	$pegawai = Pegawai::join('jabatan','jabatan.id_jabatan', '=', 'users.id_jabatan')
                          ->join('pendidikan','pendidikan.id_pendidikan', '=', 'users.id_pendidikan')
                          ->get();
    	return view('pegawai/index', ['pegawai'=>$pegawai,'no'=>0]);

    }

    public function create() {
    	$jabatan = Jabatan::all();
        $pendidikan = Pendidikan::all();
    	return view('pegawai/create', ['jabatan'=>$jabatan], ['pendidikan'=>$pendidikan]);
    }

    public function store(Request $request) {
    	$this->validate($request,[
            'nip' => 'required|numeric',
    		'nama' => 'required|alha|min:3|max:50',
            'email'=>'required|email',
            'password'=>'required|alpha',
    		'jenis_kelamin' => 'required',
            'usia' => 'required|numeric',
            'agama'=>'required|alpha',
            'tempat_lahir' => 'required|alpha',
    		'tanggal_lahir' => 'required',
    		'jabatan' => 'required',
            'pendidikan' => 'required',
            'tahun_masuk' => 'required|numeric',
            'no_telepon' => 'required|numeric|max:13',
            'alamat' => 'required',
    		'foto' => 'required',
    	], [
            'nip.required' => 'nip pegawai tidak boleh kosong',
    		'nama.required' => 'nama pegawai tidak boleh kosong',
            'email.required' => 'email itu penting',
            'password.required' => 'password itu Juga Penting',
    		'jenis_kelamin.required' => 'jenis kelamin tidak boleh kosong',
            'usia.required' => 'usia tidak boleh kosong',
            'agama.reqiured' => 'apa agama anda?',
            'tempat_lahir.required' => 'tempat_lahir tidak boleh kosong',
    		'tanggal_lahir.required' => 'tanggal lahir tidak boleh kosong',
    		'jabatan.required' => 'jabatan tidak boleh kosong',
            'pendidikan.required' => 'pendidikan tidak boleh kosong',
            'tahun_masuk.required' => 'tahun masuk tidak boleh kosong',
            'no_telepon.required' => 'no_telepon tidak boleh kosong',
    		'alamat.required' => 'alamat tidak boleh kosong',
    		'foto.required' => 'foto tidak boleh kosong',
    	]);

    	if($request->hasfile('foto'))
    	{
    		$file = $request->file('foto');
    		$namafile=time().$file->getClientOriginalName();
    		$file->move(public_path().'/images/', $namafile);
    	}

    	$pegawai = new Pegawai;
        $pegawai->nip = $request['nip'];
    	$pegawai->nama_pegawai = $request['nama'];
        $pegawai->email = $request['email'];
        $pegawai->password = bcrypt($request['password']);
    	$pegawai->jenis_kelamin = $request['jenis_kelamin'];
        $pegawai->usia = $request['usia'];
        $pegawai->agama = $request['agama'];
        $pegawai->tempat_lahir = $request['tempat_lahir'];
    	$pegawai->tanggal_lahir = $request['tanggal_lahir'];
    	$pegawai->id_jabatan = $request['jabatan'];
        $pegawai->id_pendidikan = $request['pendidikan'];
        $pegawai->tahun_masuk = $request['tahun_masuk'];
        $pegawai->no_telepon = $request['no_telepon'];
    	$pegawai->alamat = $request['alamat'];
    	$pegawai->foto = $namafile;
        $pegawai->save();

    	return redirect() 
    		->route('pegawai.index')
    		->with('success','Data berhasil ditambahkan');
    }

    public function show($id)
    {
        $pegawai = Pegawai::find($id);
        $jabatan = Jabatan::all();
        $pendidikan = Pendidikan::all();
        return view('pegawai.detail',['pegawai' => $pegawai, 'jabatan' => $jabatan, 'pendidikan' => $pendidikan]);
    }

    public function edit($id) {
    	$pegawai = Pegawai::find($id);
    	$jabatan = Jabatan::all();
        $pendidikan = Pendidikan::all();
    	$l = ($pegawai['jenis_kelamin'] == "Laki-laki") ? "checked" : "";
    	$p = ($pegawai['jenis_kelamin'] == "Perempuan") ? "checked" : "";
    	return view('pegawai/edit', ['pegawai'=>$pegawai, 'jabatan'=>$jabatan, 'pendidikan'=>$pendidikan, 'l'=>$l, 'p'=>$p]);
    }

    public function update(Request $request, $id) {
    	$this->validate($request, [
            'nip' => 'required|numeric',
            'nama' => 'required|alha|min:3|max:50',
            'email'=>'required|email',
            'password'=>'required|alpha',
            'jenis_kelamin' => 'required',
            'usia' => 'required|numeric',
            'agama'=>'required|alpha',
            'tempat_lahir' => 'required|alpha',
            'tanggal_lahir' => 'required',
            'jabatan' => 'required',
            'pendidikan' => 'required',
            'tahun_masuk' => 'required|numeric',
            'no_telepon' => 'required|numeric|max:13',
            'alamat' => 'required',
            'foto' => 'required',
    	], [
            'nip.required' => 'nip pegawai tidak boleh kosong',
            'nama.required' => 'nama pegawai tidak boleh kosong',
            'email.required' => 'email itu penting',
            'password.required' => 'password itu Juga Penting',
            'jenis_kelamin.required' => 'jenis kelamin tidak boleh kosong',
            'usia.required' => 'usia tidak boleh kosong',
            'agama.reqiured' => 'apa agama anda?',
            'tempat_lahir.required' => 'tempat_lahir tidak boleh kosong',
            'tanggal_lahir.required' => 'tanggal lahir tidak boleh kosong',
            'jabatan.required' => 'jabatan tidak boleh kosong',
            'pendidikan.required' => 'pendidikan tidak boleh kosong',
            'tahun_masuk.required' => 'tahun masuk tidak boleh kosong',
            'no_telepon.required' => 'no_telepon tidak boleh kosong',
            'alamat.required' => 'alamat tidak boleh kosong',
            'foto.required' => 'foto tidak boleh kosong',
    	]);

    	$ubahfile = false;
    	if($request->hasfile('foto'))
    	{
    		$file = $request->file('foto');
    		$namafile=time().$file->getClientOriginalName();
    		$file->move(public_path().'/images/', $namafile);
    		$ubahfile = true;
    	}

    	$pegawai = Pegawai::find($id);
        $pegawai->nip = $request['nip'];
    	$pegawai->nama_pegawai = $request['nama'];
    	$pegawai->jenis_kelamin = $request['jenis_kelamin'];
        $pegawai->usia = $request['usia'];
        $pegawai->tempat_lahir = $request['tempat_lahir'];
    	$pegawai->tanggal_lahir = $request['tanggal_lahir'];
    	$pegawai->id_jabatan = $request['jabatan'];
        $pegawai->id_pendidikan = $request['pendidikan'];
        $pegawai->tahun_masuk = $request['tahun_masuk'];
        $pegawai->no_telepon = $request['no_telepon'];
        $pegawai->alamat = $request['alamat'];
    	if($ubahfile){
    		unlink(public_path().'/images/'.$pegawai->foto);
    		$pegawai->foto = $namafile;
    	}
    	$pegawai->update();

    	return redirect()
    		->route('pegawai.index')
    		->with('success', 'Data berhasil di edit');
    }

    public function destroy($id) {
    	$pegawai = Pegawai::find($id);
    	$pegawai->delete();
    	unlink(public_path().'/images/'.$pegawai->foto);

    	return redirect()
    		->route('pegawai.index')
    		->with('success', 'Data berhasil di hapus');
    }
}

resources/views/pegawai/create.blade.php
@extends('layouts.template')

@section('title','Form Pegawai')

@section('content')
<h4 class="mt-2">Tambah Pegawai</h4>
<hr>

@if ($errors->any())
	<div class="alert alert-danger pb-0">
		<ul>
			@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
@endif

<form method="post" action="{{ route('pegawai.store') }}" enctype="multipart/form-data">
	{{ csrf_field() }}

	<div class="form-group row">
		<label for="nip" class="col-sm-2 col-form-label">NIP</label>
		<div class="col-sm-6">
			<input class="form-control" type="text" id="nip" name="nip" autocomplete="off" autofocus="">
		</div>
	</div>

	<div class="form-group row">
		<label for="nama" class="col-sm-2 col-form-label">Nama</label>
		<div class="col-sm-6">
			<input class="form-control" type="text" id="nama" name="nama" autocomplete="off" autofocus="">
		</div>
	</div>

	<div class="form-group row">
		<label for="email" class="col-sm-2 col-form-label">Email</label>
		<div class="col-sm-6">
			<input class="form-control" type="text" id="email" name="email" autocomplete="off" autofocus="">

              @if ($errors->has('email'))
                 <span class="invalid-feedback" role="alert">
                      <strong>{{ $errors->first('email') }}</strong>
                 </span>
              @endif
		</div>
	</div>

	<div class="form-group row">
		<label for="password" class="col-sm-2 col-form-label">Password</label>
		<div class="col-sm-6">
			<input class="form-control" type="text" id="password" name="password" autocomplete="off" autofocus="">
			  @if ($errors->has('password'))
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $errors->first('password') }}</strong>
                  </span>
              @endif
		</div>
	</div>
	 <div class="form-group row">
      <label for="password-confirm" class="col-sm-2 col-form-label">Confirm Password</label>
		<div class="col-md-6">
            <input id="password-confirm" type="password" class="form-control" autocomplete="off" name="password_confirmation" required>
            </div>
    </div>

	<div class="form-group row">
		<label class="col-sm-2 col-form-label">Jenis Kelamin</label>
		<div class="col-sm-6">
			<div class="custom-control custom-radio custom-control-inline">
				<input class="custom-control-input" type="radio" id="jkl" name="jenis_kelamin" value="Laki-laki">
				<label class="custom-control-label" for="jkl">Laki-laki</label>
			</div>
			<div class="custom-control custom-radio custom-control-inline">
				<input class="custom-control-input" type="radio" id="jkp" name="jenis_kelamin" value="Perempuan">
				<label class="custom-control-label" for="jkp">Perempuan</label>
			</div>
		</div>
	</div>

	<div class="form-group row">
		<label for="usia" class="col-sm-2 col-form-label">Usia</label>
		<div class="col-sm-6">
			<input class="form-control" type="text" id="usia" name="usia" autocomplete="off" autofocus="">
		</div>
	</div>

	<div class="form-group row">
		<label for="agama" class="col-sm-2 col-form-label">Agama</label>
		<div class="col-sm-6">
			<select class="custom-select" id="agama" name="agama">
				<option value="">--Pilih Agama--</option>
				<option value="islam">Islam</option>
				<option value="Kristen Protestan">Kristen Protestan</option>
				<option value="Kristen Katolik">Kristen Katolik</option>
				<option value="hindu">Hindu</option>
				<option value="bhuda">Bhuda</option>
				<option value="Khonghucu">Khonghucu</option>
			</select>
		</div>
	</div>

	<div class="form-group row">
		<label for="tempat_lahir" class="col-sm-2 col-form-label">Tempat Lahir</label>
		<div class="col-sm-6">
			<input class="form-control" type="text" id="tempat_lahir" name="tempat_lahir" autocomplete="off" autofocus="">
		</div>
	</div>

	<div class="form-group row">
		<label for="tanggal_lahir" class="col-sm-2 col-form-label">Tanggal Lahir</label>
		<div class="col-sm-6">

			<input class="form-control" type="date" id="tanggal_lahir" name="tanggal_lahir">
		</div>
	</div>

	<div class="form-group row">
		<label for="jabatan" class="col-sm-2 col-form-label">Pendidikan</label>
		<div class="col-sm-6">
			<select class="custom-select" id="pendidikan" name="pendidikan">
				<option value="">--Pilih Pendidikan--</option>
				@foreach($pendidikan as $p){
				<option value="{{ $p['id_pendidikan'] }}"> {{ $p['nama_pendidikan'] }}</option>";
				@endforeach
			</select>
		</div>
	</div>

	<div class="form-group row">
		<label for="jabatan" class="col-sm-2 col-form-label">Jabatan</label>
		<div class="col-sm-6">
			<select class="custom-select" id="jabatan" name="jabatan">
				<option value="">--Pilih Jabatan--</option>
				@foreach($jabatan as $j){
				<option value="{{ $j['id_jabatan'] }}"> {{ $j['nama_jabatan'] }}</option>";
				@endforeach
			</select>
		</div>
	</div>

	<div class="form-group row">
		<label for="tahun_masuk" class="col-sm-2 col-form-label">Tahun Masuk</label>
		<div class="col-sm-6">
			<input class="form-control" type="text" id="tahun_masuk" name="tahun_masuk" autocomplete="off" autofocus="">
		</div>
	</div>

	<div class="form-group row">
		<label for="no_telepon" class="col-sm-2 col-form-label">Nomor Telepon</label>
		<div class="col-sm-6">
			<input class="form-control" type="text" id="no_telepon" name="no_telepon" autocomplete="off" autofocus="">
		</div>
	</div>

	<div class="form-group row">
		<label for="alamat" class="col-sm-2 col-form-label">Alamat</label>
		<div class="col-sm-6">
			<textarea class="form-control" id="alamat" name="alamat" autocomplete="off" autofocus=""></textarea>
		</div>
	</div>

	<div class="form-group row">
		<label class="col-sm-2 col-form-label">Foto</label>
		<div class="col-sm-6">
			<div class="custom-file">
				<input class="custom-file-input" type="file" id="inputGroupFile02" name="foto">
				<label for="foto" class="custom-file-label">Pilih file</label>
			</div>
		</div>
	</div>

	<button type="submit" class="btn btn-outline-info btn-fw"><i class="oi oi-task"></i>Simpan</button>
	<button type="reset" class="btn btn-outline-danger btn-fw"><i class="oi oi-circle-x"></i>Batal</button>

</form>
	</div>
	</div>
</div>
@endsection

resources/views/pegawai/detail.blade.php
@extends('layouts.template')

@section('content')
<h4 class="mt-2">Detail Pegawai</h4>

@if ($errors->any())
	<div class="alert alert-danger pb-0">
		<ul>
			@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
@endif

	{{ method_field('PUT') }}
	{{ csrf_field() }}

	<div class="form-group row">
		<label for="nip" class="col-sm-2 col-form-label">NIP</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" id="nip" name="nip" autocomplete="off" autofocus="" value="{{ $pegawai['nip'] }}">
		</div>
	</div>

	<div class="form-group row">
		<label for="nama" class="col-sm-2 col-form-label">Nama</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" id="nama" name="nama" autocomplete="off" autofocus="" value="{{ $pegawai['nama_pegawai'] }}">
		</div>
	</div>

	<div class="form-group row">
		<label for="email" class="col-sm-2 col-form-label">Email</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" id="email" name="email" autocomplete="off" autofocus="" value="{{ $pegawai['email'] }}">
		</div>
	</div>

	<div class="form-group row">
<label class="col-sm-2 col-form-label">Jenis Kelamin</label>
<div class="col-sm-4">
<input class="form-control" type="text" id="" name="jenkel" value="{{ $pegawai['jenis_kelamin']}}">
		</div>
	</div>

	<div class="form-group row">
		<label for="usia" class="col-sm-2 col-form-label">Usia</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" id="usia" name="usia" autocomplete="off" autofocus="" value="{{ $pegawai['usia'] }}">
		</div>
	</div>

	<div class="form-group row">
		<label for="tempat_lahir" class="col-sm-2 col-form-label">Tempat Lahir</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" id="tempat_lahir" name="tempat_lahir" autocomplete="off" autofocus="" value="{{ $pegawai['tempat_lahir'] }}">
		</div>
	</div>

	<div class="form-group row">
		<label for="tanggal_lahir" class="col-sm-2 col-form-label">Tanggal Lahir</label>
		<div class="col-sm-3">
			<input class="form-control" type="date" id="tanggal_lahir" name="tanggal_lahir" value="{{ $pegawai['tanggal_lahir'] }}">
		</div>
	</div>

	<div class="form-group row">
		<label for="pendidikan" class="col-sm-2 col-form-label">pendidikan</label>
		<div class="col-sm-4">
			<select class="custom-select" id="pendidikan" name="pendidikan">
				<option value="">--Pilih Pendidikan--</option>
				@foreach($pendidikan as $p){
				<option value="{{ $p['id_pendidikan'] }}"
				@if($p['id_pendidikan'] == $pegawai['id_pendidikan'])selected @endif>
				{{ $p['nama_pendidikan'] }}</option>";
				@endforeach
			</select>
		</div>
	</div>

	<div class="form-group row">
		<label for="jabatan" class="col-sm-2 col-form-label">Jabatan</label>
		<div class="col-sm-4">
			<select class="custom-select" id="jabatan" name="jabatan">
				<option value="">--Pilih Jabatan--</option>
				@foreach($jabatan as $j){
				<option value="{{ $j['id_jabatan'] }}"
				@if($j['id_jabatan'] == $pegawai['id_jabatan'])selected @endif>
				{{ $j['nama_jabatan'] }}</option>";
				@endforeach
			</select>
		</div>
	</div>

	<div class="form-group row">
		<label for="tahun_masuk" class="col-sm-2 col-form-label">Tahun Masuk</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" id="tahun_masuk" name="tahun_masuk" autocomplete="off" autofocus="" value="{{ $pegawai['tahun_masuk'] }}">
		</div>
	</div>

	<div class="form-group row">
		<label for="no_telepon" class="col-sm-2 col-form-label">Nomor Telepon</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" id="no_telepon" name="no_telepon" autocomplete="off" autofocus="" value="{{ $pegawai['no_telepon'] }}">
		</div>
	</div>

	<div class="form-group row">
		<label for="alamat" class="col-sm-2 col-form-label">Alamat</label>
		<div class="col-sm-8">
			<textarea class="form-control" rows="5" id="alamat" name="alamat" autocomplete="off" autofocus="">{{ $pegawai['alamat'] }}</textarea>
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-4">
			<div class="custom-file">
				Foto
			</div>
		<img class="img-thumbnail mt-2" src="{{ asset('images/'.$pegawai['foto']) }}" width="150">
		</div>
	</div>

	<button type="submit" class="btn btn-outline-info btn-fw"><i class="oi oi-task"></i> Simpan </button>
	<button type="reset" class="btn btn-outline-danger btn-fw"><i class="oi oi-circle-x"></i> Batal </button>

</form>
@endsection

resources/views/pegawai/edit.blade.php
@extends('layouts.template')

@section('content')
<h4 class="mt-2">Edit Pegawai</h4>

@if ($errors->any())
	<div class="alert alert-danger pb-0">
		<ul>
			@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
@endif

<form method="post" action="{{ route('pegawai.update', $pegawai['id']) }}" enctype="multipart/form-data">
	{{ method_field('PUT') }}
	{{ csrf_field() }}

	<div class="form-group row">
		<label for="nip" class="col-sm-2 col-form-label">NIP</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" id="nip" name="nip" autocomplete="off" autofocus="" value="{{ $pegawai['nip'] }}">
		</div>
	</div>

	<div class="form-group row">
		<label for="nama" class="col-sm-2 col-form-label">Nama</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" id="nama" name="nama" autocomplete="off" autofocus="" value="{{ $pegawai['nama_pegawai'] }}">
		</div>
	</div>

	<div class="form-group row">
		<label for="email" class="col-sm-2 col-form-label">Email</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" id="email" name="email" autocomplete="off" autofocus="" value="{{ $pegawai['email'] }}">
		</div>
	</div>

	<div class="form-group row">
		<label class="col-sm-2 col-form-label">Jenis Kelamin</label>
		<div class="col-sm-4">
			<div class="custom-control custom-radio custom-control-inline">
				<input class="custom-control-input" type="radio" id="jkl" name="jenis_kelamin" value="Laki-laki" {{ $l }}>
				<label class="custom-control-label" for="jkl">Laki-laki</label>
			</div>
			<div class="custom-control custom-radio custom-control-inline">
				<input class="custom-control-input" type="radio" id="jkp" name="jenis_kelamin" value="Perempuan" {{ $p }}>
				<label class="custom-control-label" for="jkp">Perempuan</label>
			</div>
		</div>
	</div>

	<div class="form-group row">
		<label for="usia" class="col-sm-2 col-form-label">Usia</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" id="usia" name="usia" autocomplete="off" autofocus="" value="{{ $pegawai['usia'] }}">
		</div>
	</div>

	<div class="form-group row">
		<label for="tempat_lahir" class="col-sm-2 col-form-label">Tempat Lahir</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" id="tempat_lahir" name="tempat_lahir" autocomplete="off" autofocus="" value="{{ $pegawai['tempat_lahir'] }}">
		</div>
	</div>

	<div class="form-group row">
		<label for="tanggal_lahir" class="col-sm-2 col-form-label">Tanggal Lahir</label>
		<div class="col-sm-3">
			<input class="form-control" type="date" id="tanggal_lahir" name="tanggal_lahir" value="{{ $pegawai['tanggal_lahir'] }}">
		</div>
	</div>

	<div class="form-group row">
		<label for="pendidikan" class="col-sm-2 col-form-label">pendidikan</label>
		<div class="col-sm-4">
			<select class="custom-select" id="pendidikan" name="pendidikan">
				<option value="">--Pilih Pendidikan--</option>
				@foreach($pendidikan as $p){
				<option value="{{ $p['id_pendidikan'] }}"
				@if($p['id_pendidikan'] == $pegawai['id_pendidikan'])selected @endif>
				{{ $p['nama_pendidikan'] }}</option>";
				@endforeach
			</select>
		</div>
	</div>

	<div class="form-group row">
		<label for="jabatan" class="col-sm-2 col-form-label">Jabatan</label>
		<div class="col-sm-4">
			<select class="custom-select" id="jabatan" name="jabatan">
				<option value="">--Pilih Jabatan--</option>
				@foreach($jabatan as $j){
				<option value="{{ $j['id_jabatan'] }}"
				@if($j['id_jabatan'] == $pegawai['id_jabatan'])selected @endif>
				{{ $j['nama_jabatan'] }}</option>";
				@endforeach
			</select>
		</div>
	</div>

	<div class="form-group row">
		<label for="tahun_masuk" class="col-sm-2 col-form-label">Tahun Masuk</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" id="tahun_masuk" name="tahun_masuk" autocomplete="off" autofocus="" value="{{ $pegawai['tahun_masuk'] }}">
		</div>
	</div>

	<div class="form-group row">
		<label for="no_telepon" class="col-sm-2 col-form-label">Nomor Telepon</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" id="no_telepon" name="no_telepon" autocomplete="off" autofocus="" value="{{ $pegawai['no_telepon'] }}">
		</div>
	</div>

	<div class="form-group row">
		<label for="alamat" class="col-sm-2 col-form-label">Alamat</label>
		<div class="col-sm-8">
			<textarea class="form-control" rows="5" id="alamat" name="alamat" autocomplete="off" autofocus="">{{ $pegawai['alamat'] }}</textarea>
		</div>
	</div>

	<div class="form-group row">
		<label class="col-sm-2 col-form-label">Foto</label>
		<div class="col-sm-4">
			<div class="custom-file">
				<input class="custom-file-input" type="file" id="inputGroupFile02" name="foto">
				<label for="foto" class="custom-file-label">Ubah file</label>
			</div>
		<img class="img-thumbnail mt-2" src="{{ asset('images/'.$pegawai['foto']) }}" width="150">
		</div>
	</div>

	<button type="submit" class="btn btn-outline-info btn-fw"><i class="oi oi-task"></i> Simpan </button>
	<button type="reset" class="btn btn-outline-danger btn-fw"><i class="oi oi-circle-x"></i> Batal </button>

</form>
@endsection

resources/views/pegawai/index.blade.php
@extends('layouts.template')
@section('content')


<h4 class="mt-2">Data Pegawai</h4>
<hr>
<a class="btn btn-inverse-primary btn-fw" href="{{ route('pegawai.create') }}"><i class="oi oi-plus"></i> Tambah </a>

@if ($message = Session::get('success'))
	<div class="alert alert-success mt-3 pb-0">
		<p>{{ $message }}</p>
	</div>
@endif

<div class="table-responsive mt-3">
<table class="table table-striped table-hover table-bordered" id="myTable">
	<thead>
		<tr>
			<th>No</th>
			<th>NIP</th>
			<th>Nama</th>
			<th>Jenis Kelamin</th>
			<th>Alamat</th>
			<th>Foto</th>
			<th>Aksi</th>
		</tr>
	</thead>
	<tbody>
@foreach($pegawai as $data)
	<tr>
		<td><?php echo ++$no ?></td>
		<td>{{$data['nip']}}</td>
		<td>{{$data['nama_pegawai']}}</td>
		<td>{{$data['jenis_kelamin']}}</td>
		<td>{{$data['alamat']}}</td>
		<td><img src="{{ asset('/images/'.$data['foto']) }}" width="100"></td>
		<td>
			<a class="btn btn-outline-success btn-fw" href="{{ route('pegawai.edit', $data['id']) }}"> <i class="oi oi-pencil"></i> Edit </a>
			<form class="d-inline" method="post" action="{{ route('pegawai.destroy', $data['id']) }}">
				{{ method_field('DELETE') }}
				{{ csrf_field() }}
				<button type="submit" class="btn btn-outline-danger btn-fw"> <i class="oi oi-trash"></i> Hapus </button>
			</form>
			<a href="{{ route('pegawai.show',$data['id']) }}" class="btn btn-outline-warning btn-fw"> Detail </a>
		</td>
	</tr>
@endforeach
	</tbody>
</table>
</div>

@endsection